### ISSUE TITLE
for prop getting changed to htmlFor and breaking the tabs

### ISSUE THREAD

**Issue by MattJakeman** [patrik-piskay/react-tabs-redux#10]
Hi,

I have configured the tabs as guided by the examples and have the following simple code for some tabs:

EDIT : Apologies for the poor code formatting, I can't seem to get it to display correctly.

```
<Tabs activeLinkStyle={tabStyles.activeLinkStyle}
                  visibleTabStyle={tabStyles.visibleTabStyle}
                  style={tabStyles.tabs}>
              <div style={tabStyles.links}>
                <TabLink to='liveTab' style={tabStyles.tabLink}>Live</TabLink>
                <TabLink to='recordedTab' style={tabStyles.tabLink}>Recorded</TabLink>
              </div>
              <div style={tabStyles.content}>
                <TabContent for='liveTab'>
                  <h2>TEST</h2>
                </TabContent>
                <TabContent for='recordedTab'>
                  <h2>This is the recorded tab</h2>
                </TabContent>
              </div>
            </Tabs>
```

However, I am getting the following warning and although I can change tabs, the tab content is never displayed for either tab:

> Warning: Failed prop type: The prop `for` is marked as required in `TabContent`, but its value is `undefined`.

Upon inspecting the react code in the dev tools it seems the 'for' prop is being changed to 'htmlFor'. Is this the normal behaviour and there is another issue I have not found as to why the content isn't being displayed upon changing tabs?

Thanks for your help.

**Comment by patrik-piskay** [comment]
Hi Matt, can you specify which version of `react` and `react-dom` packages are you running?

**Comment by MattJakeman** [comment]
Hi Patrik,

Thanks for the rapid response. It is using version 15.3.2

Cheers
Matt

**Comment by patrik-piskay** [comment]
No worries. I will only have time to investigate on Saturday though.

It might be related to the latest react version so if you'd prefer you can always downgrade to the version the examples are running on and if we confirm it's being caused by the current React version, we'd do a fix and a major release that could be used with the latest React version.

**Comment by MattJakeman** [comment]
Ok thanks. Hopefully I will get a chance to investigate this tomorrow so I will downgrade and report back so that you will at least know if that's the issue. Do you know the react version the examples are working on?

**Comment by MattJakeman** [comment]
Just saw your edit as I sent that. I'll try an early 15.x.x version. Thanks.

**Comment by MattJakeman** [comment]
I've tried with 15.0.0, and also went back to 0.14.8 just in case and the issue is still there, so something else must be wrong with my code somewhere. I'm wondering if it's because I'm trying to use it inside a [react-burger-manu](https://github.com/negomi/react-burger-menu). I'll keep digging.

**Comment by MattJakeman** [comment]
I can confirm it's not to do with the react-burger-menu package as I have tried it at a top level now and the problem still persists. I'm stumped now as to what could be causing it.

**Comment by patrik-piskay** [comment]
Hi @MattJakeman, so I just tried running examples from this repo on the latest React version and it's working correctly. Seems like it's some other dependency in your project causing this. Aren't you using any babel plugin that would "autocorrect" html attributes for js properties (`class` to `className`, `for` to `htmlFor`)?

Also, if you would create a repo where the issue would be reproducible I'd take a look there.

**Comment by patrik-piskay** [comment]
[This plugin](https://github.com/insin/babel-plugin-react-html-attrs) would cause this for you Matt, are you using it?

**Comment by MattJakeman** [comment]
Hi Patrick,

Thanks for looking into this. I've just checked and it looks like one of the other devs had installed that package without me noticing so it looks like that's the cause.

**Comment by patrik-piskay** [comment]
No worries, good that we found the cause. It also exposed a potential issue that might be worth fixing in the future - changing `to` and `for` props in `Tab` component for something more specific.
