### ISSUE TITLE
Make class names customizable

### ISSUE THREAD

**Issue by andrew-tam-000** [patrik-piskay/react-tabs-redux#14]
Any chance we can make the class names for each component customizable?

Would just be supporting a className prop for each component, as well as an activeClassName / visibleClassName where applicable.  And if none supplied, then we just fallback to the defaults that you've provided?

I can look into submitting a PR

**Comment by patrik-piskay** [comment]
Sure, let's do this.

**Comment by andrew-tam-000** [comment]
Woot ok, submitted a PR @patrik-piskay .

In addition to this, since we are adding the ability to have custom classes, should we also have the ability to remove the default inline styles?  This would give the option to make your library less smart about hiding / showing tabs, and instead allow users full ability to control the hide / show state.

I'll go ahead and submit a PR, and then we'll see what ya think :)

**Comment by flienteen** [comment]
Can you make a new npm release with this changes?
Thanks.

**Comment by patrik-piskay** [comment]
Released as 1.5.0 now
