### ISSUE TITLE
Components disappear

### ISSUE THREAD

**Issue by davayd** [patrik-piskay/react-tabs-redux#15]
Your manual says, that TabLink and TabContent can be nested. But after wrapping them with the <div> tag, they are not rendered on the page 
I repeat your example (https://github.com/patrik-piskay/react-tabs-redux/blob/master/examples/plain-react/src/index.js), but components whatever don't render. When I delete <div> tags, everything is working!
My scss file: https://ufile.io/4e64d
Browser: https://ufile.io/1fcd41
My declaration:
```
     <Tabs className="tabs">
        <div className="tab-links">
          <TabLink to="tender">Тендер</TabLink>
          <TabLink to="lots">Лоты</TabLink>
          <TabLink to="documents">Документы</TabLink>
        </div>
        <div className="content">
          <TabContent for="tender">tenders</TabContent>
          <TabContent for="lots">lots</TabContent>
          <TabContent for="documents">documents</TabContent>
        </div>
      </Tabs>
```

**Comment by patrik-piskay** [comment]
Hi @davayd, I can confirm your snippet works for me. Can you inspect the code in browser using [React devtools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi)? One possible reason why it doesn't work for you is that your setup (maybe a babel plugin?) changes prop names on `TabLink`/`TabContent` components.
