### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead

### ISSUE THREAD

**Issue by rahul-desai3** [patrik-piskay/react-tabs-redux#20]
I migrated `react-tabs-redux` to the latest version (`1.5.0`) from `v1.4.1` but I'm still getting this warning.

![screen shot 2017-05-05 at 4 26 23 pm](https://cloud.githubusercontent.com/assets/2539881/25767589/b1ffffde-31af-11e7-9639-cd8952581949.png)

**Comment by patrik-piskay** [comment]
Hi @rahul-desai3, sorry for a late response. Would you like to send a PR fixing this? If not, I'll have some spare time next week.

**Comment by patrik-piskay** [comment]
I'll merged the PR, I'll review and publish possibly tomorrow.
