### ISSUE TITLE
TabIndexes not respected between tabs

### ISSUE THREAD

**Issue by w35l3y** [patrik-piskay/react-tabs-redux#24]
When navigating input fields with TAB button, tabindex is not respected probably because of the "display: none" on the tab content.
I am trying to swap the active tab when navigating with TAB button, but I am starting to think it would be great to see it implemented natively.

The following source is related to jQuery, but I think it is just a matter of CSS:
https://stackoverflow.com/questions/16860619/setting-tab-index-usefully-when-some-fields-are-hidden-by-css-in-an-accordion-c

**Comment by patrik-piskay** [comment]
Hey @w35l3y, I totally didn't receive email notification about this issue :/
Do you think you could send a PR addressing it?
