### ISSUE TITLE
How active tab specified?

### ISSUE THREAD

**Issue by GuillermoParedes** [patrik-piskay/react-tabs-redux#25]
Hello guys, I need help.

I want redirect to tab specified, but  by onClick button on my screen

**Comment by w35l3y** [comment]
Are you using Redux ?
There is an attribute called `selectedTab`.
Just call an action to change the value of this attribute to the name of desired tab.

https://github.com/patrik-piskay/react-tabs-redux/blob/master/examples/redux/src/components/index.js
In this case, you could call the action `changeSelectedTab(selectedTab, tabNamespace)`.

**Comment by patrik-piskay** [comment]
Hi @GuillermoParedes, here you can see how this could be implemented: https://codesandbox.io/s/VQL0kJ5z

All you need is to provide `selectedTab` and `handleSelect` props to the `Tabs` component and keep the information about which tab is selected in the component state. That way tabs could be changed either by clicking on `TabLink` components or by clicking on buttons
