### ISSUE TITLE
How do I make TabLink focusable?

### ISSUE THREAD

**Issue by rahul-desai3** [patrik-piskay/react-tabs-redux#29]
With tab navigation, I would like the user to focus the `TabLink`. I tried setting `tabIndex="0"` on the `TabLink` but it was not rendered in the `<div class="tab-link">` in the DOM.

How do I fix this?

**Comment by patrik-piskay** [comment]
Hey @rahul-desai3, I've implemented a solution for this, in 2 steps:

1. you can pass any prop to `<TabLink />` (like `tabIndex`) now and it will be passed to the underlying HTML element
2. this alone would help you much as you would be able to switch focus on different tabs but you would have to implement `onKeyPress` behaviour yourself too. So the 2nd step is that by default, `tabIndex="0"` is set on each `<TabLink />` with `onKeyPress` handler to change tabs on `space` or `enter` key press as I think this behaviour should be supported out of the box

I am going to release this as a breaking change as `tabIndex="0"` means all TabLinks get `:focus` styles applied which might or might not be desired.

**Comment by patrik-piskay** [comment]
You can see it working here https://codesandbox.io/s/q7w6221pz6 with `react-tabs-redux@2.0.0`

**Comment by rahul-desai3** [comment]
@patrik-piskay That was fast! Thank you.

**Comment by rahul-desai3** [comment]
@patrik-piskay I am using `react@15.5.3` in my project. When I try to install `react-tabs-redux@2.0.0`, I am getting this error:

`npm ERR! peerinvalid Peer react-tabs-redux@2.0.0 wants react@^0.14.5 || >15`

I cannot upgrade my react version just yet since the other modules that I am using do not support v16 yet and my application breaks if I do so.

Can you please make `react-tabs-redux` support `react@15.5.3` along with the `tabIndex` fix?

**Comment by patrik-piskay** [comment]
Fixed!

**Comment by rahul-desai3** [comment]
Works perfectly! Thank you for the quick turnaround.
