### ISSUE TITLE
Possible to use 'display: "flex"' instead of 'display: "block"' on content?

### ISSUE THREAD

**Issue by fromanother** [patrik-piskay/react-tabs-redux#3]
When clicking a tab, it's corresponding content get set the style `display: block`. Is it possible to change this?

I'd like to use `display: flex`

**Comment by patrik-piskay** [comment]
Hi @fromanother, I've just released a new version that allows this use case. Please follow [this readme change](https://github.com/patrik-piskay/react-tabs-redux/commit/9975a12d0091d402a9960beee374a737f5ac85c8) ([code change](https://github.com/patrik-piskay/react-tabs-redux/commit/eac5480be94537130a5f8b0e9b4b3a5513a841ce))

Basically you have 2 options now. Either specify `visibleTabStyle` on `<Tabs />` component or use global `tab-content-visible` class name to change styles. Please be aware that if you go for the class name solution, you will have to override `display` with `!important` flag (as the original `display: block` will still be set as inline style).
