### ISSUE TITLE
Accessibility issue found using react-a11y

### ISSUE THREAD

**Issue by rahul-desai3** [patrik-piskay/react-tabs-redux#31]
I have been using the NPM module [react-a11y](https://www.npmjs.com/package/react-a11y) to test my project for accessibility. Following is the warning it is throwing:
```
TabLink You have a click handler on a non-interactive element but no `role` DOM property. It will be unclear what this element is supposed to do to a screen-reader user. http://www.w3.org/TR/wai-aria/roles#role_definitions
```

I get 10 of these warning even though I have only 1 tab in my project (eventually I will be having more).

![screen shot 2017-10-18 at 10 50 59 am](https://user-images.githubusercontent.com/2539881/31734058-55889a52-b3f2-11e7-8c79-cff6a1e7ad20.png)

How do I fix this?

**Comment by patrik-piskay** [comment]
You can either pass `role="button"` to each `<TabLink>` component and see if it helps, or (preferably :) submit a PR to add `role="button"` and `aria-pressed` ([docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role)) so it's handled on this package's level.

**Comment by rahul-desai3** [comment]
I was able to fix this by setting `role="button"` and the `onKeyDown` event handler on the `<TabLink>`. Thank you.
