### ISSUE TITLE
Rerendering TabLink Contents onChange

### ISSUE THREAD

**Issue by Siyanda-Mzam** [patrik-piskay/react-tabs-redux#34]
How would I render, to the `TabLink`, changes that happen in a Redux Store? It seems that the `TabLinks` only render once and are not aware of any changes that may happen from a Redux Store.

**Comment by patrik-piskay** [comment]
Not sure what you mean exactly @Siyanda-Mzam. Do you mind sharing a short piece of code demonstrating what you are trying to achieve?

[This line](https://github.com/patrik-piskay/react-tabs-redux/blob/master/examples/redux/src/components/index.js#L43) demonstrates how you can pass the information about which tab is selected (retrieved from Redux store)

**Comment by Siyanda-Mzam** [comment]
Thanks for the speedy reply. What I would like to achieve is passing props as children of the TabLink and am expecting the TabLink children to reflect any changes that may occur on these props.

For instance: 

```<TabLink>{this.props.items.length}</TabLink>```
Initially displays zero. When the items are incremented in the store, the TabLink does not rerender to reflect the changed prop. It remains the same. The only time it changes is when I literally called `this,forceUpdate`, which is not the approach I would like to apply.

**Comment by patrik-piskay** [comment]
It looks like your app preventing rerenders (maybe `shouldComponentUpdate`?)

This should definitely work as `react-tabs-redux` doesn't implement any cSU logic. You can check it working [here](https://codesandbox.io/s/vw2m3p7ky) - tab name is changed every second and read from redux store

**Comment by Siyanda-Mzam** [comment]
Hmm, wow, that is interesting. I see it's working, but on my side, this approach only seems to work if the redux changes are made from the tabs point, i.e. they are propagated through from other components to the tabs. I will investigate even further and will get back to you if it does not seem to work.

**Comment by Siyanda-Mzam** [comment]
Thank you very much for the feedback. I realised that there issue really was with my logic. Also thanks very much for this package. It is very useful.
