### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by m1lk1way** [patrik-piskay/react-tabs-redux#37]
Hey, are you going to add typescript typings?

**Comment by patrik-piskay** [comment]
Hey, I personally don't use typescript, but if you'd like to open a PR with the typings, I'll happily merge it in!

**Comment by ntnbrtnkv** [comment]
Typings are available now in DefinitelyTyped repo `npm i @types/react-tabs-redux`.

**Comment by patrik-piskay** [comment]
is there a way we can include them in this package as well?

**Comment by ntnbrtnkv** [comment]
Since typings already has been published throught `@types`, I think it is not good idea:
- 2 sources of typings will confuse people
- it will requre installing TS stuff and adding configurations, and maintining it
- code quality in DT repo will be better because the repo has expirienced TS devs for review

**Comment by patrik-piskay** [comment]
Fair enough. Should we at least make a note in the readme about it? Or is DT a go-to place for TS devs for library types already, so there is no need for mentioning it in this repo?

**Comment by ntnbrtnkv** [comment]
TS compiler show friendly message if no typings are provided by library itself:
`error TS7016: Could not find a declaration file for module 'react-tabs-redux'. 'C:/tmp/node_modules/react-tabs-redux/lib/index.js' implicitly has an 'any' type.
  Try 'npm install @types/react-tabs-redux' if it exists or add a new declaration (.d.ts) file containing declare module 'react-tabs-redux';`

Honestly, I never saw any mentions abount `@types` in readme

**Comment by patrik-piskay** [comment]
Great, thank you! Closing this then
