### ISSUE TITLE
Trigger an event on first Tab Select

### ISSUE THREAD

**Issue by danielesalvatore** [patrik-piskay/react-tabs-redux#38]
Dear all, 
thank you for this amazing library. 

I would like to achieve the following: I need to track (for analytic purpose) each tab selection. The "change of tab" can be easily achieved using the library with the `redux`'s approach and the `handleSelect` in which I can trigger both the "tab change" event and the "track tab change one.

My problem is that (i think correctly from the library point of view) `handleSelect` when the first time the selected tab is shown. 

How would you address the need to track even the first tab rendering?

Thank you in avance

**Comment by patrik-piskay** [comment]
Hey @danielesalvatore, thanks for the suggestion! `onChange` was added that gets called on the initial render and on any subsequent tab changes. Hope that'll work for you!

I'll release the change shortly.

**Comment by danielesalvatore** [comment]
@patrik-piskay Thank you very much for your support!

**Comment by patrik-piskay** [comment]
Released in `3.1.0`

**Comment by danielesalvatore** [comment]
Hi again @patrik-piskay FYI I just update the library to `4.0.0` but it doesn't seem to include the feature

**Comment by patrik-piskay** [comment]
Can you provide an example of what's not working? `onChange` prop on `<Tabs />` is supported in `4.0.0`
