### ISSUE TITLE
TabContent

### ISSUE THREAD

**Issue by char0n** [patrik-piskay/react-tabs-redux#7]
Hi,

This is only a question/suggestion. In TabContent source code I did not find any option to disable rendering when content is not visible. In my app I have quite a lot of tabs and every content gets interpreted event if if doesn't need to. I don't need any animations when switching tabs either.

I would suggest to introduce new prop called forceRenderTabPanel (on Tabs component) with default value of `true` to keep the backward compatibility  just like in https://github.com/reactjs/react-tabs. Do you think it is a good idea for this project ? If yes I would try to provide pull request for this feature.

Thanks

**Comment by patrik-piskay** [comment]
Actually that's a good idea! 

I would only name the prop more like `renderActiveTabContentOnly` and default it to false (to not break v1 code). But I think defaulting to true probably makes more sense so we can do a v2 release (with the changed default) after shipping it to v1.

I'll be waiting for the PR if you are interested!

**Comment by char0n** [comment]
Ok deal. I'll provide pull request myself in a couple of days

**Comment by patrik-piskay** [comment]
Hey @char0n, have you made any progress on this?

**Comment by char0n** [comment]
Ah, It has been already 21 days. I am sorry. I have been caught up in my job a little bit. I will try to produce pull request tomorow. I have some time in the evening.

**Comment by patrik-piskay** [comment]
No worries, just wanted to know what's the status, if you still want to do it. I'll leave this open and will wait for the PR then.

**Comment by patrik-piskay** [comment]
Fixed by https://github.com/patrik-piskay/react-tabs-redux/pull/8
